### PR TITLE
Majorly rearranged AddToDownloads

### PR DESCRIPTION
**Pull request by Chdata**
Based off of what I did on my private server... it should work. Needs
in-game testing.

Rewrote AddToDownload to organize it a little better. It's now split with all the files relevant to specific bosses in order, and based on whether or not we're only Precaching (it exists in TF2/HL2 already) or if it's a custom file that's being downloaded.

Additionally, I added the old HHH Theme to sound/, and the entirety of the FastDL files (including the new theme).

### CODE REVIEW

**Comment by WildCard65** [comment]
@Chdata

**Comment by Chdata** [comment]
Was only HHH's theme broken? Was it broken as in you heard the sd_doomsday_event song? Or just nothing played at all? Is CBS's theme broken for you?

As for the other sounds... looking over the code they are there. Are you sure they're on your server with the fastDL files (I assume that's set up fine)? Try deleting them from 

C:\Program Files (x86)\Steam\SteamApps\common\Team Fortress 2\tf\download\sound\saxton_hale

On the computer you play the game on, to allow the server to redownload it. Also delete any .cache files in tf/.

If that doesn't work... then it's that mysterious Valve glitch where files that are there and work for some people, aren't working for others. I've had it happen for a few things myself.

**Comment by yarik2720** [comment]
Not only HHH, CBS too.. also hale event sounds are not working.. deleting sounds from client side didn't helps.. sounds from server with fastdl downloads well.

Failed to load sound "saxton_hale\lolwut_1.wav", file probably missing from disk/repository
Failed to load sound "saxton_hale\vagineer_responce_jump_1.wav", file probably missing from disk/repository

And that problem is not only for me. Also tried to play game on another pc, all materials, models and sounds downloads well, but clients tells errors

**Comment by WildCard65** [comment]
are you sure the client aren't redownloading the files constantly?

**Comment by yarik2720** [comment]
after reconnecting it doesn't redownloading existing files.
all files are ok http://puu.sh/e6ZmP.png

**Comment by Chdata** [comment]
I guess it's the same problem as seen here:
https://forums.alliedmods.net/showthread.php?t=244209&page=31

**Comment by yarik2720** [comment]
no problems with models or materials (except of easter egg missed material, but have no error in console)
ss 2015-01-05 at 09 45 11

**Comment by yarik2720** [comment]
@Chdata, tried to update sourcemod and metamod to latest versions (Metamod:Source version 1.10.5-dev, Build ID: 927:896d7dc/ SourceMod Version: 1.6.4-dev+4621) nothing changed.
also, all sounds of easter bunny are working.. it is only one boss, where sounds are completely working

**Comment by Chdata** [comment]
FlaminSarge doesn't seem to know what's up with downloads either =/

All I can say is... there was one particular file I deleted then allowed to redownload. Except redownloading didn't immediately fix it, and it was still appearing as "missing file disk/repository". But then for no reason, a few days later, the file started working again.

**Pull request merged**
