### PR TITLE
translatable damage HUD

### PR DESCRIPTION
**Pull request by yarik2720**
probably not best implemention

### CODE REVIEW

**Comment by WildCard65** [comment]
@Chdata @FlaminSarge What you think about this?

**Comment by FlaminSarge** [comment]
Should probably just have both strings entirely as translations, then. Reason is that it currently hardcodes "{dmgtranslation}: # - **{name}'s {dmgtranslation}**: #" which may not be the correct order for all languages.

**Comment by yarik2720** [comment]
tried to make it with 3 variables, but instead of nickname were showed up players id.
like that:
ShowSyncHudText(client, rageHUD, "%t", "vsh_damage_others", Damage[client], obstarget, Damage[obstarget]);
where vsh_damage_others was
Damage: {1} - {2}'s Damage: {3}.

**Comment by Chdata** [comment]
If it shows up with a client id instead of their name, you need to change

**Comment by yarik2720** [comment]
thanks @Chdata, fixed that

**Comment by WildCard65** [comment]
I'll let @Chdata or @FlaminSarge handle merging this one.

**Pull request merged**
