### PR TITLE
Port VSH to 1.7

### PR DESCRIPTION
**Pull request by WildCard65**
This is a pretty big change for VSH as it ports VSH from 1.6 syntax over to PURE 1.7 syntax. All commits were unable to compile except for 100% Ported one as I did things in batches.

### CODE REVIEW

**Comment by WildCard65** [comment]
I need @Chdata and @FlaminSarge to test this as well as I'll get forum users to test it.

**Comment by WildCard65** [comment]
@FlaminSarge Can I merge this now?

**Comment by FlaminSarge** [comment]
I haven't had any chance to test this but I'm sure it'll be fine.

**Comment by WildCard65** [comment]
So is that a yes I can merge it?

**Pull request merged**
