### PR TITLE
Added PrecacheSound for 'BunnyRandomVoice'.

### PR DESCRIPTION
**Pull request by Starblaster64**

### CODE REVIEW

**Comment by WildCard65** [comment]
As I said b4, can you make sure your changes go into a seperate branch based off of develop.

**Comment by Starblaster64** [comment]
I'm a bit confused now, I have created a separate branch based off of develop, that is the one I created a pull request from.

**Comment by WildCard65** [comment]
I'll recheck then, maybe I misread
On 2015-01-01 7:32 PM, "Starblaster64" <notifications@github.com> wrote:
>
> I'm a bit confused now, I have created a separate branch based off of
develop, that is the one I created a pull request from.

**Comment by WildCard65** [comment]
And about PRs be merged onto develop by order of Chdata, well I asked
CHdata over steam if PRs should be to develop which Contributing.md states.
And I did misread branch info. But ya, remake your last PR

**Comment by Starblaster64** [comment]
Thanks for clearing that up, and by "last PR" do you mean the GRU/KGB one? Because I don't see the point if Chdata already pushed his own version of it.

**Comment by WildCard65** [comment]
Ya, and idk, you can check commits of develop branch

**Pull request merged**
